spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=training_management;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update